# Generated by Django 5.1.2 on 2024-10-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(choices=[('admin', 'admin'), ('product_manager', 'product_manager')], max_length=100)),
                ('fname', models.CharField(max_length=100)),
                ('mobile', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('password', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(default='', upload_to='profile_picture/')),
            ],
        ),
    ]
