# Generated by Django 5.1.2 on 2024-10-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_mst_product_sub_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_sub_cat',
            name='product_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
